# Generated by Django 5.1 on 2024-08-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2D_Ventures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_picture',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.TextField(blank=True),
        ),
    ]
